import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs/promises';
const app=await fs.readFile(new URL('app.js',import.meta.url),'utf8');
const source=app.slice(app.indexOf('function popoverOpen('),app.indexOf('async function init('));
const events={},panels=['language-menu','navigation-dialog'].map(id=>({id,dataset:{},hidden:false,contains:target=>target.id===id,dispatchEvent(event){this.lastState=event.newState;}}));
const buttons=panels.map(panel=>({id:panel.id}));
const document={querySelectorAll:()=>panels,querySelector:selector=>buttons[panels.findIndex(panel=>selector.includes(panel.id))],addEventListener:(type,fn)=>events[type]=fn};
vm.runInNewContext(source+';supportPopovers();',{document,HTMLElement:class {},Event:class {constructor(type){this.type=type;}}});
assert(panels.every(panel=>panel.hidden));
buttons[0].onclick();assert(!panels[0].hidden);assert(panels[1].hidden);assert.equal(panels[0].lastState,'open');
buttons[1].onclick();assert(panels[0].hidden);assert(!panels[1].hidden);
events.pointerdown({target:{closest:()=>null,id:'outside'}});assert(panels.every(panel=>panel.hidden));
buttons[1].onclick();events.keydown({key:'Escape'});assert(panels.every(panel=>panel.hidden));
buttons[0].onclick();buttons[0].onclick();assert(panels[0].hidden);
console.log('Older Chrome: menus initially hidden, one menu open, button toggle, outside dismissal and Escape verified.');

const progressSource=app.slice(app.indexOf('function setupSceneProgress('),app.indexOf('function scrollScene('));
const progressEvents={},moves=[];let scene=3,clock=0;
const range={min:'0',max:'9',value:'3',disabled:false,addEventListener(type,fn,options){progressEvents[type]={fn,options};}};
vm.runInNewContext(progressSource+';setupSceneProgress(range,n=>{moves.push(n);scene=n;},()=>scene);',{range,moves,performance:{now:()=>clock}});
range.value='7';progressEvents.input.fn();assert.equal(moves.at(-1),7);
const wheel=(deltaY,extra={})=>{let prevented=false;progressEvents.wheel.fn({deltaY,deltaX:0,preventDefault(){prevented=true;},...extra});return prevented;};
assert(wheel(80));assert.equal(moves.at(-1),8);wheel(80);assert.equal(moves.length,2);
clock=200;wheel(-80);assert.equal(moves.at(-1),7);
clock=400;wheel(0,{deltaX:80});assert.equal(moves.at(-1),8);
range.value='9';progressEvents.input.fn();clock=600;wheel(80);assert.equal(moves.at(-1),9);
range.value='0';progressEvents.input.fn();clock=800;wheel(-80);assert.equal(moves.at(-1),0);
assert.equal(wheel(80,{ctrlKey:true}),false);range.disabled=true;assert.equal(wheel(80),false);
assert.equal(progressEvents.wheel.options.passive,false);
console.log('Scene scrubber: direct seeking, wheel direction/throttle, book boundaries and browser zoom preserved.');
