import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const source=(await readFile(new URL('./annotations.js',import.meta.url),'utf8')).replace('export function','function');
async function setup(nav={}){
 const elements=new Map(),downloads=[];let verseRect={top:400,bottom:430,left:200,right:400,width:200};
 const el=id=>{if(!elements.has(id))elements.set(id,{value:'',textContent:'',hidden:false,disabled:false,style:{},setAttribute(name,value){this[name]=value;},getBoundingClientRect(){return id==='reader'?{top:200,bottom:740}:{width:220,height:50};},addEventListener(type,fn){this[type]=fn;},showModal(){this.open=true;},close(){this.open=false;},focus(){this.focused=true;},select(){this.selected=true;}});return elements.get(id);};
 const verse={dataset:{chapter:'5',verse:'30'},querySelector(){return {textContent:'나는 나의 원대로 하려 하지 않고',getBoundingClientRect:()=>verseRect};},closest(){return {dataset:{id:'1'}};}};
 const ctx={drawImage(){},createLinearGradient(){return {addColorStop(){}};},fillRect(){},fillText(){},measureText(){return {width:10};}};
 const document={getElementById:el,addEventListener(){},fonts:{ready:Promise.resolve()},createElement(tag){return tag==='canvas'?{getContext:()=>ctx,toBlob:fn=>fn(new Blob(['png'],{type:'image/png'}))}:{click(){downloads.push(this);}};}};
 vm.runInNewContext(source+'\nannotations(()=>({bookId:"john",data:{book:"요한복음",scenes:[{id:1,image:"scene.jpg"}]}}));',{document,navigator:nav,localStorage:{getItem:()=>null},window:{innerHeight:800,innerWidth:1280,addEventListener(){}},requestAnimationFrame:fn=>{fn();return 1;},cancelAnimationFrame(){},Image:class {width=1600;height=900;async decode(){}},File,Blob,URL,setTimeout,clearTimeout});
 el('reader').click({target:{closest:()=>({closest:()=>verse})}});
 assert.equal(el('selection-tools').style.top,'340px');assert.equal(el('selection-tools').style.left,'190px');
 verseRect={top:205,bottom:235,left:2,right:202,width:200};el('reader').scroll();assert.equal(el('selection-tools').style.top,'245px');assert.equal(el('selection-tools').style.left,'12px');
 verseRect={top:900,bottom:930,left:200,right:400,width:200};el('reader').scroll();assert.equal(el('selection-tools').hidden,true);
 verseRect={top:400,bottom:430,left:200,right:400,width:200};el('reader').scroll();assert.equal(el('selection-tools').hidden,false);
 el('share-selection').onclick();assert.equal(el('selection-tools').hidden,true);
 await new Promise(resolve=>setImmediate(resolve));
 assert.equal(el('share-card').disabled,false);
 return {el,downloads};
}
const calls=[];let supported=true;
const native=await setup({canShare:p=>supported&&p.files?.[0] instanceof File,share:async p=>calls.push(p)});
await native.el('share-card').onclick();
assert.deepEqual(Object.keys(calls[0]),['files']);assert.equal(calls[0].files[0].type,'image/png');assert.equal(calls[0].files[0].name,'vible-john-5-30.png');
await native.el('share-url-selection').onclick();assert.equal(calls[1].url,'https://vible.now/?book=john&chapter=5&verse=30');assert.equal(calls[1].files,undefined);assert.equal(calls[1].text,undefined);
supported=false;await native.el('share-card').onclick();assert.equal(native.downloads.length,1);
let copied;const fallback=await setup({clipboard:{writeText:async text=>copied=text}});fallback.el('note-dialog').close();await fallback.el('share-url-selection').onclick();assert.equal(fallback.el('note-dialog').open,true);assert.equal(copied,fallback.el('share-url').value);await fallback.el('share-card').onclick();assert.equal(fallback.downloads.length,1);
const denied=await setup({});await denied.el('copy-link').onclick();assert(denied.el('share-url').selected);
const cancel=await setup({canShare:()=>true,share:async()=>{throw Object.assign(new Error(),{name:'AbortError'});}});const before=cancel.el('note-status').textContent;await cancel.el('share-card').onclick();await cancel.el('share-link').onclick();assert.equal(cancel.downloads.length,0);assert.equal(cancel.el('note-status').textContent,before);
const failed=await setup({canShare:()=>true,share:async()=>{throw new Error('blocked');}});await failed.el('share-card').onclick();assert.match(failed.el('note-status').textContent,/이미지 저장/);await failed.el('share-link').onclick();assert.match(failed.el('note-status').textContent,/URL 복사/);
console.log('Selection toolbar positioning/scroll and sharing verified: actual PNG, verse URL, download/copy fallback, denied clipboard, cancellation and errors.');
