// Generated by review/build-epistles-catalog.py. Scripture remains in data/*.json.
export const epistleMetadata = [
  {
    "id": "1corinthians",
    "name": "고린도전서",
    "english": "1 Corinthians",
    "code": "1CO",
    "chapters": 16,
    "verseCount": 437
  },
  {
    "id": "2corinthians",
    "name": "고린도후서",
    "english": "2 Corinthians",
    "code": "2CO",
    "chapters": 13,
    "verseCount": 256
  },
  {
    "id": "galatians",
    "name": "갈라디아서",
    "english": "Galatians",
    "code": "GAL",
    "chapters": 6,
    "verseCount": 149
  },
  {
    "id": "ephesians",
    "name": "에베소서",
    "english": "Ephesians",
    "code": "EPH",
    "chapters": 6,
    "verseCount": 155
  },
  {
    "id": "philippians",
    "name": "빌립보서",
    "english": "Philippians",
    "code": "PHP",
    "chapters": 4,
    "verseCount": 104
  },
  {
    "id": "colossians",
    "name": "골로새서",
    "english": "Colossians",
    "code": "COL",
    "chapters": 4,
    "verseCount": 95
  },
  {
    "id": "1thessalonians",
    "name": "데살로니가전서",
    "english": "1 Thessalonians",
    "code": "1TH",
    "chapters": 5,
    "verseCount": 89
  },
  {
    "id": "2thessalonians",
    "name": "데살로니가후서",
    "english": "2 Thessalonians",
    "code": "2TH",
    "chapters": 3,
    "verseCount": 47
  },
  {
    "id": "1timothy",
    "name": "디모데전서",
    "english": "1 Timothy",
    "code": "1TI",
    "chapters": 6,
    "verseCount": 113
  },
  {
    "id": "2timothy",
    "name": "디모데후서",
    "english": "2 Timothy",
    "code": "2TI",
    "chapters": 4,
    "verseCount": 83
  },
  {
    "id": "titus",
    "name": "디도서",
    "english": "Titus",
    "code": "TIT",
    "chapters": 3,
    "verseCount": 46
  },
  {
    "id": "philemon",
    "name": "빌레몬서",
    "english": "Philemon",
    "code": "PHM",
    "chapters": 1,
    "verseCount": 25
  },
  {
    "id": "hebrews",
    "name": "히브리서",
    "english": "Hebrews",
    "code": "HEB",
    "chapters": 13,
    "verseCount": 303
  },
  {
    "id": "james",
    "name": "야고보서",
    "english": "James",
    "code": "JAS",
    "chapters": 5,
    "verseCount": 108
  },
  {
    "id": "1peter",
    "name": "베드로전서",
    "english": "1 Peter",
    "code": "1PE",
    "chapters": 5,
    "verseCount": 105
  },
  {
    "id": "2peter",
    "name": "베드로후서",
    "english": "2 Peter",
    "code": "2PE",
    "chapters": 3,
    "verseCount": 61
  },
  {
    "id": "1john",
    "name": "요한일서",
    "english": "1 John",
    "code": "1JN",
    "chapters": 5,
    "verseCount": 105
  },
  {
    "id": "2john",
    "name": "요한이서",
    "english": "2 John",
    "code": "2JN",
    "chapters": 1,
    "verseCount": 13
  },
  {
    "id": "3john",
    "name": "요한삼서",
    "english": "3 John",
    "code": "3JN",
    "chapters": 1,
    "verseCount": 15
  },
  {
    "id": "jude",
    "name": "유다서",
    "english": "Jude",
    "code": "JUD",
    "chapters": 1,
    "verseCount": 25
  }
];
export const epistleBooks = {
  "1corinthians": {
    "name": "고린도전서",
    "english": "1 CORINTHIANS",
    "storyTitle": "사랑으로 세워지는 공동체",
    "storyCopy": "십자가의 지혜, 한 몸의 은사, 사랑과 부활의 소망.",
    "context": "십자가의 지혜, 한 몸의 은사, 사랑과 부활의 소망.",
    "search": "사랑, 믿음, 소망…",
    "plan": "1corinthians-image-plan.json",
    "arcs": [
      {
        "chapters": "1–4장",
        "title": "십자가의 지혜와 공동체",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "5–10장",
        "title": "거룩한 삶과 자유",
        "copy": "",
        "chapter": 5
      },
      {
        "chapters": "11–14장",
        "title": "한 몸의 은사와 사랑",
        "copy": "",
        "chapter": 11
      },
      {
        "chapters": "15–16장",
        "title": "부활의 소망",
        "copy": "",
        "chapter": 15
      }
    ],
    "chapterNames": [
      "고린도의 성도들에게 은혜와 평강",
      "말의 화려함보다 십자가",
      "시기와 분쟁, 아직 자라지 못한 마음",
      "맡은 자에게 구할 것은 충성",
      "악을 자랑하지 말고 아파하라",
      "형제의 다툼을 지혜롭게 풀다",
      "부부가 서로를 돌보며 합의하다",
      "지식은 교만하게, 사랑은 세우다",
      "너희가 사도 됨의 증거",
      "구름과 바다, 광야의 공급",
      "본받고 전해 받은 것을 지키다",
      "성령을 따라 주를 고백하다",
      "사랑이 없으면 아무것도 아니다",
      "사랑을 따라 공동체를 세우는 말",
      "전해 받은 복음 위에 굳게 서다",
      "성도들을 위한 준비된 연보"
    ]
  },
  "2corinthians": {
    "name": "고린도후서",
    "english": "2 CORINTHIANS",
    "storyTitle": "연약함 안에 드러나는 위로",
    "storyCopy": "고난과 화해, 아낌없는 나눔, 약한 자를 붙드는 은혜.",
    "context": "고난과 화해, 아낌없는 나눔, 약한 자를 붙드는 은혜.",
    "search": "사랑, 믿음, 소망…",
    "plan": "2corinthians-image-plan.json",
    "arcs": [
      {
        "chapters": "1–2장",
        "title": "고난 속의 위로",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "3–5장",
        "title": "새 언약과 질그릇의 보배",
        "copy": "",
        "chapter": 3
      },
      {
        "chapters": "6–7장",
        "title": "열린 마음과 기쁨",
        "copy": "",
        "chapter": 6
      },
      {
        "chapters": "8–9장",
        "title": "함께 나누는 은혜",
        "copy": "",
        "chapter": 8
      },
      {
        "chapters": "10–13장",
        "title": "연약함과 진실한 사도 됨",
        "copy": "",
        "chapter": 10
      }
    ],
    "chapterNames": [
      "아가야의 모든 성도에게 평강",
      "넘치는 사랑으로 쓴 눈물의 편지",
      "너희가 살아 있는 편지",
      "낙심하지 않고 진리를 드러내다",
      "장막을 넘어 영원한 처소를 바라보다",
      "지금은 은혜 받을 때",
      "약속을 붙들고 거룩함을 이루다",
      "가난 중에도 자원한 풍성한 나눔",
      "억지가 되지 않도록 미리 준비하다",
      "온유와 관용으로 권하다",
      "진실하고 깨끗한 마음을 지키다",
      "말할 수 없는 환상과 계시",
      "진실을 확인하고 약함 속의 능력을"
    ]
  },
  "galatians": {
    "name": "갈라디아서",
    "english": "GALATIANS",
    "storyTitle": "자유를 주시는 복음",
    "storyCopy": "은혜로 시작한 믿음에서 성령을 따라 서로 섬기는 자유로.",
    "context": "은혜로 시작한 믿음에서 성령을 따라 서로 섬기는 자유로.",
    "search": "사랑, 믿음, 소망…",
    "plan": "galatians-image-plan.json",
    "arcs": [
      {
        "chapters": "1–2장",
        "title": "하나의 복음",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "3–4장",
        "title": "약속과 믿음",
        "copy": "",
        "chapter": 3
      },
      {
        "chapters": "5–6장",
        "title": "사랑으로 살아내는 자유",
        "copy": "",
        "chapter": 5
      }
    ],
    "chapterNames": [
      "은혜로 부르시고 건지시는 복음",
      "함께 복음을 확인하다",
      "듣고 믿음으로 시작한 성령의 삶",
      "상속자라도 어렸을 때는",
      "다시는 종의 멍에를 메지 말라",
      "온유하게 바로잡고 자신도 살피다"
    ]
  },
  "ephesians": {
    "name": "에베소서",
    "english": "EPHESIANS",
    "storyTitle": "함께 지어져 가는 하나님의 집",
    "storyCopy": "은혜로 살아난 사람들이 한 몸을 이루고 사랑 가운데 걷습니다.",
    "context": "은혜로 살아난 사람들이 한 몸을 이루고 사랑 가운데 걷습니다.",
    "search": "사랑, 믿음, 소망…",
    "plan": "ephesians-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "은혜와 부르심",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "2–3장",
        "title": "화해와 한 몸",
        "copy": "",
        "chapter": 2
      },
      {
        "chapters": "4–5장",
        "title": "새 사람의 삶",
        "copy": "",
        "chapter": 4
      },
      {
        "chapters": "6장",
        "title": "담대히 서는 믿음",
        "copy": "",
        "chapter": 6
      }
    ],
    "chapterNames": [
      "신실한 성도들에게 은혜와 평강",
      "허물 속에 죽었던 삶",
      "갇힌 자리에서 알려진 비밀",
      "온유와 오래 참음, 평안의 매는 줄",
      "사랑 가운데 행하라",
      "부모를 공경하는 자녀"
    ]
  },
  "philippians": {
    "name": "빌립보서",
    "english": "PHILIPPIANS",
    "storyTitle": "갇힌 자리에서도 이어지는 기쁨",
    "storyCopy": "그리스도의 겸손을 따르며 함께 달리고 서로의 필요를 돌봅니다.",
    "context": "그리스도의 겸손을 따르며 함께 달리고 서로의 필요를 돌봅니다.",
    "search": "사랑, 믿음, 소망…",
    "plan": "philippians-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "복음 안의 기쁨",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "2장",
        "title": "낮아지심과 함께 섬김",
        "copy": "",
        "chapter": 2
      },
      {
        "chapters": "3장",
        "title": "앞을 향해 달리는 믿음",
        "copy": "",
        "chapter": 3
      },
      {
        "chapters": "4장",
        "title": "평안과 감사의 나눔",
        "copy": "",
        "chapter": 4
      }
    ],
    "chapterNames": [
      "빌립보의 모든 성도에게",
      "같은 사랑으로 마음을 합하다",
      "육체의 자랑보다 주 안의 기쁨",
      "기쁨과 면류관인 너희, 굳게 서라"
    ]
  },
  "colossians": {
    "name": "골로새서",
    "english": "COLOSSIANS",
    "storyTitle": "그리스도 안에 깊이 뿌리내리다",
    "storyCopy": "그리스도의 충만함 안에서 옛 삶을 벗고 감사와 사랑으로 살아갑니다.",
    "context": "그리스도의 충만함 안에서 옛 삶을 벗고 감사와 사랑으로 살아갑니다.",
    "search": "사랑, 믿음, 소망…",
    "plan": "colossians-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "모든 것의 중심이신 그리스도",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "2장",
        "title": "그 안에서 굳게 서다",
        "copy": "",
        "chapter": 2
      },
      {
        "chapters": "3장",
        "title": "새 사람의 삶",
        "copy": "",
        "chapter": 3
      },
      {
        "chapters": "4장",
        "title": "기도와 동역의 인사",
        "copy": "",
        "chapter": 4
      }
    ],
    "chapterNames": [
      "골로새의 신실한 형제들에게",
      "얼굴을 못 보아도 사랑으로 연합",
      "위의 것을 찾는 새 생명",
      "상전도 의와 공평으로"
    ]
  },
  "1thessalonians": {
    "name": "데살로니가전서",
    "english": "1 THESSALONIANS",
    "storyTitle": "서로를 위로하며 기다리는 소망",
    "storyCopy": "사랑의 수고와 거룩한 삶, 죽음 앞에서도 서로를 붙드는 소망.",
    "context": "사랑의 수고와 거룩한 삶, 죽음 앞에서도 서로를 붙드는 소망.",
    "search": "사랑, 믿음, 소망…",
    "plan": "1thessalonians-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "믿음과 사랑의 수고",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "2–3장",
        "title": "진실한 돌봄과 그리움",
        "copy": "",
        "chapter": 2
      },
      {
        "chapters": "4장",
        "title": "거룩한 삶과 부활의 위로",
        "copy": "",
        "chapter": 4
      },
      {
        "chapters": "5장",
        "title": "깨어 서로를 세우다",
        "copy": "",
        "chapter": 5
      }
    ],
    "chapterNames": [
      "세 동역자의 은혜와 평강",
      "고난을 지나 담대하게 전하다",
      "디모데를 보내 믿음을 굳게",
      "배운 삶을 더욱 힘써 행하라",
      "때를 계산하지 않고 준비하다"
    ]
  },
  "2thessalonians": {
    "name": "데살로니가후서",
    "english": "2 THESSALONIANS",
    "storyTitle": "흔들림 속에서도 굳게 서다",
    "storyCopy": "고난 속의 인내와 분별, 평온히 일하고 선을 행하는 공동체.",
    "context": "고난 속의 인내와 분별, 평온히 일하고 선을 행하는 공동체.",
    "search": "사랑, 믿음, 소망…",
    "plan": "2thessalonians-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "고난 속의 인내",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "2장",
        "title": "두려움에 휩쓸리지 않는 분별",
        "copy": "",
        "chapter": 2
      },
      {
        "chapters": "3장",
        "title": "기도와 책임 있는 삶",
        "copy": "",
        "chapter": 3
      }
    ],
    "chapterNames": [
      "성도들에게 다시 은혜와 평강",
      "이미 왔다는 말에 두려워하지 말라",
      "말씀이 달음질하도록 기도"
    ]
  },
  "1timothy": {
    "name": "디모데전서",
    "english": "1 TIMOTHY",
    "storyTitle": "믿음의 집을 돌보는 마음",
    "storyCopy": "바른 가르침과 기도, 사람을 존중하는 돌봄과 경건한 삶.",
    "context": "바른 가르침과 기도, 사람을 존중하는 돌봄과 경건한 삶.",
    "search": "사랑, 믿음, 소망…",
    "plan": "1timothy-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "은혜와 바른 가르침",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "2–3장",
        "title": "기도와 공동체의 섬김",
        "copy": "",
        "chapter": 2
      },
      {
        "chapters": "4장",
        "title": "말과 삶의 본",
        "copy": "",
        "chapter": 4
      },
      {
        "chapters": "5장",
        "title": "세대를 돌보는 교회",
        "copy": "",
        "chapter": 5
      },
      {
        "chapters": "6장",
        "title": "경건과 자족",
        "copy": "",
        "chapter": 6
      }
    ],
    "chapterNames": [
      "참 아들 디모데에게 긍휼과 평강",
      "모든 사람과 권세자를 위한 기도",
      "돌봄의 직분과 절제의 성품",
      "외식의 금지보다 선한 창조를",
      "세대를 가족처럼 존중하다",
      "역사 속 일터에서 신실하게"
    ]
  },
  "2timothy": {
    "name": "디모데후서",
    "english": "2 TIMOTHY",
    "storyTitle": "끝까지 지키는 믿음의 바통",
    "storyCopy": "두려움을 넘어 복음을 맡기고, 어려움 속에서도 말씀과 사랑을 지킵니다.",
    "context": "두려움을 넘어 복음을 맡기고, 어려움 속에서도 말씀과 사랑을 지킵니다.",
    "search": "사랑, 믿음, 소망…",
    "plan": "2timothy-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "다시 불붙이는 믿음",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "2장",
        "title": "신실하게 맡기고 견디다",
        "copy": "",
        "chapter": 2
      },
      {
        "chapters": "3장",
        "title": "말씀 안에 머물다",
        "copy": "",
        "chapter": 3
      },
      {
        "chapters": "4장",
        "title": "끝까지 달린 길과 마지막 인사",
        "copy": "",
        "chapter": 4
      }
    ],
    "chapterNames": [
      "사랑하는 아들에게 생명의 약속",
      "충성된 사람들에게 다시 맡기다",
      "경건의 모양과 무너진 관계",
      "때를 얻든 못 얻든 말씀을 전하라"
    ]
  },
  "titus": {
    "name": "디도서",
    "english": "TITUS",
    "storyTitle": "은혜가 바꾸는 일상의 삶",
    "storyCopy": "바른 가르침이 세대와 가정을 돌보고, 선한 일을 준비하는 삶으로 이어집니다.",
    "context": "바른 가르침이 세대와 가정을 돌보고, 선한 일을 준비하는 삶으로 이어집니다.",
    "search": "사랑, 믿음, 소망…",
    "plan": "titus-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "신실하게 돌보는 지도자",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "2장",
        "title": "세대를 잇는 경건과 은혜",
        "copy": "",
        "chapter": 2
      },
      {
        "chapters": "3장",
        "title": "긍휼로 새로워진 삶",
        "copy": "",
        "chapter": 3
      }
    ],
    "chapterNames": [
      "진리와 영생의 소망, 디도에게",
      "세대를 돌보는 바른 가르침",
      "순종과 관용, 모든 사람에게 온유"
    ]
  },
  "philemon": {
    "name": "빌레몬서",
    "english": "PHILEMON",
    "storyTitle": "종을 넘어 사랑하는 형제로",
    "storyCopy": "바울의 간청을 따라 오네시모를 새로운 관계 안에서 받아들이는 편지.",
    "context": "바울의 간청을 따라 오네시모를 새로운 관계 안에서 받아들이는 편지.",
    "search": "사랑, 믿음, 소망…",
    "plan": "philemon-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "감사에서 시작되는 사랑의 간청",
        "copy": "",
        "chapter": 1
      }
    ],
    "chapterNames": [
      "갇힌 바울과 집에 모인 교회에"
    ]
  },
  "hebrews": {
    "name": "히브리서",
    "english": "HEBREWS",
    "storyTitle": "더 좋은 소망을 붙들고 걷다",
    "storyCopy": "그리스도와 새 언약, 믿음의 증인들, 오래 견디며 서로를 격려하는 길.",
    "context": "그리스도와 새 언약, 믿음의 증인들, 오래 견디며 서로를 격려하는 길.",
    "search": "사랑, 믿음, 소망…",
    "plan": "hebrews-image-plan.json",
    "arcs": [
      {
        "chapters": "1–3장",
        "title": "아들을 통하여 들려온 말씀",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "4–6장",
        "title": "안식과 긍휼의 대제사장",
        "copy": "",
        "chapter": 4
      },
      {
        "chapters": "7–9장",
        "title": "더 좋은 언약",
        "copy": "",
        "chapter": 7
      },
      {
        "chapters": "10장",
        "title": "담대히 나아가는 믿음",
        "copy": "",
        "chapter": 10
      },
      {
        "chapters": "11–12장",
        "title": "믿음의 증인들과 인내의 길",
        "copy": "",
        "chapter": 11
      },
      {
        "chapters": "13장",
        "title": "사랑과 감사로 살아가다",
        "copy": "",
        "chapter": 13
      }
    ],
    "chapterNames": [
      "선지자를 거쳐 아들로 말씀하시다",
      "큰 구원을 놓쳐 떠내려가지 말라",
      "집과 집 지은 이, 깊이 생각하라",
      "들음에 믿음을 함께 두다",
      "연약한 이들을 용납하는 제사장",
      "터만 다시 닦지 말고 온전함으로",
      "멜기세덱과 평강의 기억",
      "참 장막을 바라보는 큰 대제사장",
      "첫 장막의 등대와 떡상",
      "반복된 제사와 그림자의 한계",
      "바라는 것의 실상, 보이지 않는 확신",
      "무거운 것을 벗고 인내로 달리자",
      "형제 사랑과 낯선 이를 대접하라"
    ]
  },
  "james": {
    "name": "야고보서",
    "english": "JAMES",
    "storyTitle": "들은 말씀을 손과 발로",
    "storyCopy": "시험 중의 인내, 차별 없는 사랑, 말의 절제와 실제로 돕는 믿음.",
    "context": "시험 중의 인내, 차별 없는 사랑, 말의 절제와 실제로 돕는 믿음.",
    "search": "사랑, 믿음, 소망…",
    "plan": "james-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "인내와 말씀을 행하는 삶",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "2장",
        "title": "차별 없는 사랑과 살아 있는 믿음",
        "copy": "",
        "chapter": 2
      },
      {
        "chapters": "3장",
        "title": "말의 절제와 위로부터 오는 지혜",
        "copy": "",
        "chapter": 3
      },
      {
        "chapters": "4장",
        "title": "겸손히 돌이키는 마음",
        "copy": "",
        "chapter": 4
      },
      {
        "chapters": "5장",
        "title": "인내와 서로를 위한 기도",
        "copy": "",
        "chapter": 5
      }
    ],
    "chapterNames": [
      "흩어진 사람들에게 문안",
      "금가락지와 낡은 옷으로 차별하지 말라",
      "말을 맡은 이의 큰 책임",
      "욕심에서 생기는 다툼과 잘못된 간구",
      "쌓은 재물도 썩고 사라진다"
    ]
  },
  "1peter": {
    "name": "베드로전서",
    "english": "1 PETER",
    "storyTitle": "고난 속에서도 살아 있는 소망",
    "storyCopy": "나그네의 길에서 거룩함과 선한 일을 지키며 서로를 사랑합니다.",
    "context": "나그네의 길에서 거룩함과 선한 일을 지키며 서로를 사랑합니다.",
    "search": "사랑, 믿음, 소망…",
    "plan": "1peter-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "살아 있는 소망과 거룩한 삶",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "2장",
        "title": "산 돌과 선한 행실",
        "copy": "",
        "chapter": 2
      },
      {
        "chapters": "3장",
        "title": "온유한 증언과 고난",
        "copy": "",
        "chapter": 3
      },
      {
        "chapters": "4장",
        "title": "서로를 섬기는 사랑",
        "copy": "",
        "chapter": 4
      },
      {
        "chapters": "5장",
        "title": "겸손과 굳게 선 믿음",
        "copy": "",
        "chapter": 5
      }
    ],
    "chapterNames": [
      "흩어진 나그네들에게 은혜와 평강",
      "순전한 젖처럼 말씀을 사모하다",
      "행실로 드러나는 가정의 믿음",
      "남은 삶을 뜻에 따라 살다",
      "지배하지 않고 자원하여 양을 돌보다"
    ]
  },
  "2peter": {
    "name": "베드로후서",
    "english": "2 PETER",
    "storyTitle": "기억하고 자라며 기다리다",
    "storyCopy": "믿음의 성품을 더하고 거짓을 분별하며 약속을 기다리는 거룩한 삶.",
    "context": "믿음의 성품을 더하고 거짓을 분별하며 약속을 기다리는 거룩한 삶.",
    "search": "사랑, 믿음, 소망…",
    "plan": "2peter-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "믿음의 성품과 확실한 말씀",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "2장",
        "title": "거짓 가르침을 분별하다",
        "copy": "",
        "chapter": 2
      },
      {
        "chapters": "3장",
        "title": "약속을 기다리며 자라다",
        "copy": "",
        "chapter": 3
      }
    ],
    "chapterNames": [
      "같이 받은 보배로운 믿음과 평강",
      "거짓 가르침과 이익의 탐심",
      "받은 말씀을 다시 기억하게"
    ]
  },
  "1john": {
    "name": "요한일서",
    "english": "1 JOHN",
    "storyTitle": "빛 가운데 서로 사랑하다",
    "storyCopy": "생명의 말씀, 정직한 고백, 서로를 향한 사랑과 영생의 확신.",
    "context": "생명의 말씀, 정직한 고백, 서로를 향한 사랑과 영생의 확신.",
    "search": "사랑, 믿음, 소망…",
    "plan": "1john-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "생명과 빛의 사귐",
        "copy": "",
        "chapter": 1
      },
      {
        "chapters": "2장",
        "title": "말씀을 지키며 사랑하다",
        "copy": "",
        "chapter": 2
      },
      {
        "chapters": "3장",
        "title": "행함과 진실함으로",
        "copy": "",
        "chapter": 3
      },
      {
        "chapters": "4장",
        "title": "하나님께 속한 사랑",
        "copy": "",
        "chapter": 4
      },
      {
        "chapters": "5장",
        "title": "믿음과 영생의 확신",
        "copy": "",
        "chapter": 5
      }
    ],
    "chapterNames": [
      "보고 듣고 전하는 생명의 말씀",
      "우리와 온 세상을 위한 대언과 화목",
      "하나님의 자녀라 불리는 큰 사랑",
      "영들을 분별하고 참된 증언을",
      "믿음과 자녀 사랑, 무겁지 않은 계명"
    ]
  },
  "2john": {
    "name": "요한이서",
    "english": "2 JOHN",
    "storyTitle": "진리 안에서 걷는 사랑",
    "storyCopy": "사랑의 계명을 따라 걷고 그리스도의 가르침 안에 머무는 짧은 편지.",
    "context": "사랑의 계명을 따라 걷고 그리스도의 가르침 안에 머무는 짧은 편지.",
    "search": "사랑, 믿음, 소망…",
    "plan": "2john-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "진리와 사랑, 분별하는 환대",
        "copy": "",
        "chapter": 1
      }
    ],
    "chapterNames": [
      "진리와 사랑 가운데 은혜와 평강"
    ]
  },
  "3john": {
    "name": "요한삼서",
    "english": "3 JOHN",
    "storyTitle": "길을 떠난 이들을 맞아들이는 집",
    "storyCopy": "진리 안의 삶과 진실한 환대, 선을 본받는 마음을 격려합니다.",
    "context": "진리 안의 삶과 진실한 환대, 선을 본받는 마음을 격려합니다.",
    "search": "사랑, 믿음, 소망…",
    "plan": "3john-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "진리 안의 기쁨과 동역의 환대",
        "copy": "",
        "chapter": 1
      }
    ],
    "chapterNames": [
      "사랑하는 가이오에게"
    ]
  },
  "jude": {
    "name": "유다서",
    "english": "JUDE",
    "storyTitle": "긍휼 안에서 믿음을 지키다",
    "storyCopy": "왜곡된 가르침을 분별하고, 사랑 안에 머물며 서로를 긍휼히 여깁니다.",
    "context": "왜곡된 가르침을 분별하고, 사랑 안에 머물며 서로를 긍휼히 여깁니다.",
    "search": "사랑, 믿음, 소망…",
    "plan": "jude-image-plan.json",
    "arcs": [
      {
        "chapters": "1장",
        "title": "믿음을 지키는 분별과 긍휼",
        "copy": "",
        "chapter": 1
      }
    ],
    "chapterNames": [
      "사랑받고 지키심을 입은 이들에게"
    ]
  }
};
export const epistleNames = {
  "ko": {
    "1corinthians": "고린도전서",
    "2corinthians": "고린도후서",
    "galatians": "갈라디아서",
    "ephesians": "에베소서",
    "philippians": "빌립보서",
    "colossians": "골로새서",
    "1thessalonians": "데살로니가전서",
    "2thessalonians": "데살로니가후서",
    "1timothy": "디모데전서",
    "2timothy": "디모데후서",
    "titus": "디도서",
    "philemon": "빌레몬서",
    "hebrews": "히브리서",
    "james": "야고보서",
    "1peter": "베드로전서",
    "2peter": "베드로후서",
    "1john": "요한일서",
    "2john": "요한이서",
    "3john": "요한삼서",
    "jude": "유다서"
  },
  "en": {
    "1corinthians": "1 Corinthians",
    "2corinthians": "2 Corinthians",
    "galatians": "Galatians",
    "ephesians": "Ephesians",
    "philippians": "Philippians",
    "colossians": "Colossians",
    "1thessalonians": "1 Thessalonians",
    "2thessalonians": "2 Thessalonians",
    "1timothy": "1 Timothy",
    "2timothy": "2 Timothy",
    "titus": "Titus",
    "philemon": "Philemon",
    "hebrews": "Hebrews",
    "james": "James",
    "1peter": "1 Peter",
    "2peter": "2 Peter",
    "1john": "1 John",
    "2john": "2 John",
    "3john": "3 John",
    "jude": "Jude"
  },
  "ja": {
    "1corinthians": "コリントの信徒への手紙一",
    "2corinthians": "コリントの信徒への手紙二",
    "galatians": "ガラテヤの信徒への手紙",
    "ephesians": "エフェソの信徒への手紙",
    "philippians": "フィリピの信徒への手紙",
    "colossians": "コロサイの信徒への手紙",
    "1thessalonians": "テサロニケの信徒への手紙一",
    "2thessalonians": "テサロニケの信徒への手紙二",
    "1timothy": "テモテへの手紙一",
    "2timothy": "テモテへの手紙二",
    "titus": "テトスへの手紙",
    "philemon": "フィレモンへの手紙",
    "hebrews": "ヘブライ人への手紙",
    "james": "ヤコブの手紙",
    "1peter": "ペトロの手紙一",
    "2peter": "ペトロの手紙二",
    "1john": "ヨハネの手紙一",
    "2john": "ヨハネの手紙二",
    "3john": "ヨハネの手紙三",
    "jude": "ユダの手紙"
  },
  "zh": {
    "1corinthians": "哥林多前书",
    "2corinthians": "哥林多后书",
    "galatians": "加拉太书",
    "ephesians": "以弗所书",
    "philippians": "腓立比书",
    "colossians": "歌罗西书",
    "1thessalonians": "帖撒罗尼迦前书",
    "2thessalonians": "帖撒罗尼迦后书",
    "1timothy": "提摩太前书",
    "2timothy": "提摩太后书",
    "titus": "提多书",
    "philemon": "腓利门书",
    "hebrews": "希伯来书",
    "james": "雅各书",
    "1peter": "彼得前书",
    "2peter": "彼得后书",
    "1john": "约翰一书",
    "2john": "约翰二书",
    "3john": "约翰三书",
    "jude": "犹大书"
  }
};
